# Generated by Django 4.2.3 on 2023-08-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Contact',
        ),
    ]
